name: D

on:
  workflow_dispatch:
  schedule:
    - cron: '6 */12 * * *'
  watch:
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
          npm install
          npm i png-js
          npm install cron
          npm install request
          curl ipinfo.io/json
      - name: 'run sign'
        run: |
           node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: summer_movement.js
            XLC: ${{ secrets.XLC }}
            GITHUB: ${{ secrets.GITHUB }}
            EFORK: ${{ secrets.EFORK }}
            HELPURL: ${{ secrets.HELPURL }}  
