name: tn
on:
  workflow_dispatch:
  #schedule:
   #  - cron: '*/15 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajonly/1
          ref: 'main'
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          npm install
      - name: 'run ttx'
        run: |
           node tjs.js
           node txnw.js
        env:
          JRTTSIGNURL: ${{ secrets.JRTTSIGNURL }}
          JRTTSIGNKEY: ${{ secrets.JRTTSIGNKEY }}
          JRTTFARMURL: ${{ secrets.JRTTFARMURL }}
          JRTTFARMKEY: ${{ secrets.JRTTFARMKEY }}
          JRTTREADURL: ${{ secrets.JRTTREADURL }}
          JRTTREADKEY: ${{ secrets.JRTTREADKEY }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajonly/1
          ref: 'main'
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          npm install
      - name: 'run tn'
        run: |
           node txnw.js
        env:
          TXNEWS_SIGN: ${{ secrets.TXNEWS_SIGN }}
          TXNEWS_COOKIE: ${{ secrets.TXNEWS_COOKIE }}
          TXNEWS_VIDEO: ${{ secrets.TXNEWS_VIDEO }}
          XLC: ${{ secrets.XLC }}
          GITHUB: ${{ secrets.GITHUB }}      
          EFORK: ${{ secrets.EFORK }}
      - name: De Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0 
  dispatch:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: ' wait'
        run: |
          sleep 4m
          sleep $(($RANDOM%5))
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
